### ISSUE TITLE
Won't start on forge versions > 36.1.0 [nm-01] 

### ISSUE THREAD

**Issue by aburone** [KapDEK/NewMountains#1]
The maxversion is hardcoded to 36.1.0, so the game won't start if the forge version is higher.
I'm trying to use it on Forge 36.1.25

**Comment by KapDEK** [comment]
Hi, what version of the mod is this on. Is it on the 1.2.1 Beta/Pre Releases or on the 1.2 full release?

**Comment by KapDEK** [comment]
I just loaded the mod on Forge 1.16.5 36.1.31, and it worked. Maybe you are using 1.16.4 or lower? The only current supported version of the mod is 1.16.5

**Comment by KapDEK** [comment]
Wait I have figured out what went wrong! I set a setting to check the version of forge and it limited it to below 36.1.0. 
1.2.1-pre2 will fix this! Thanks for letting me know!
